### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by dragonGRaf** [AdamWHY2K/Simply_Switch_Steam_Profile_Picture#3]
WIndows 11 running exe

`Traceback (most recent call last):
  File "SSS_PFP.pyw", line 261, in <module>
    myApp.system_tray()
  File "SSS_PFP.pyw", line 244, in system_tray
    icon=Image.open("icon.ico"),
  File "PIL\Image.py", line 3227, in open
FileNotFoundError: [Errno 2] No such file or directory: 'icon.ico'
`
here the log file log:
`2023/05/28 09:42:31 AM - INFO - STARTING SSS_PFP
2023/05/28 09:42:31 AM - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2023/05/28 09:42:31 AM - DEBUG - https://api.github.com:443 "GET /repos/AdamWHY2K/Simply_Switch_Steam_Profile_Picture/releases HTTP/1.1" 200 None
2023/05/28 09:42:31 AM - INFO - Checking for update
2023/05/28 09:42:31 AM - INFO - Latest version installed
2023/05/28 09:42:31 AM - INFO - Checking file space
2023/05/28 09:42:31 AM - INFO - Getting cookies from cookiejar
2023/05/28 09:42:31 AM - DEBUG - Found SessionID
2023/05/28 09:42:31 AM - DEBUG - Found cookie
2023/05/28 09:42:31 AM - INFO - Reading settings.inc
2023/05/28 09:42:31 AM - INFO - File opened successfully
2023/05/28 09:42:31 AM - DEBUG - Found Steam64ID
2023/05/28 09:42:31 AM - INFO - Starting system tray icon
`

**Comment by dragonGRaf** [comment]
i just checked all requirements:
i have only -1mb pictures
did the settings setup
i am logged in into steam
only thing i could think of is bc im using brave browser but else :shrug:

**Comment by AdamWHY2K** [comment]
Hello fellow brave user :)

From the looks of the error message you are missing the icon.ico file, I thought the compiler I used would've included it in the .exe but I guess not. 

You can download the file you need [here](https://github.com/AdamWHY2K/Simply_Switch_Steam_Profile_Picture/blob/main/icon.ico) by clicking download raw file, make sure you save it in the same place the .exe is located and make sure it is correctly named `icon.ico`

**Comment by AdamWHY2K** [comment]
Actually, nevermind. I just released a quick hotfix so just download the latest release.

**Comment by dragonGRaf** [comment]
hello back fellow brave user xD
i will test it later thx :D
